/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Vigilant.pathfinder;

public class App {
    public String getGreeting() {
        return "Hello world!";
    }

    public static void main(String[] args) {

        Dst dst= new Dst(17);
        //Dst d=new Dst(2);
        //System.out.println(d.testMap());
        //System.out.println(dst);
        //***0=polku,1=alku,2=seinä,3=loppu***
        dst.testMap(); //luo labyrintin
        dst.testFt(); //tulostaa labyrintin 
    }
}
